version: '3.8'

services:
  bot:
    build: .
    container_name: binance-bot-container
    restart: unless-stopped
    volumes:
      # !!! ИЗМЕНЕНИЕ ЗДЕСЬ !!!
      - postgres_data_v2:/var/lib/postgresql/16/main
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/${DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      AZURE_KEYVAULT_ENABLED: false
      DB_HOST: localhost
      DB_PORT: 5432
      DB_USER:
      DB_PASSWORD:
      DB_NAME:
      TELEGRAM_ERROR_TOKEN:
      TELEGRAM_TOKEN:
      TELEGRAM_USERNAME:
      TELEGRAM_ERROR_USERNAME:
      BINANCE_API_SECRET:
      BINANCE_API_KEY:
      # Новые имена (в соответствии с ошибкой):
      binance-customer-api-key: ${BINANCE_API_KEY}
      binance-customer-secret-key: ${BINANCE_API_SECRET}
      TRADING_BOT_ENABLED:

volumes:
  # !!! И ИЗМЕНЕНИЕ ЗДЕСЬ !!!
  postgres_data_v2: