version: '3.8'

services:
  bot:
    # Указываем Portainer'у, что образ нужно собрать, а не скачивать
    build: .
    # Присваиваем имя собранному образу
    image: binance-bot-all-in-one:latest
    container_name: binance-bot-container
    restart: unless-stopped
    volumes:
      # Очень важно: сохраняем данные PostgreSQL в томе
      - postgres_data:/var/lib/postgresql/14/main
    # Переменные окружения будут добавлены вручную в UI Portainer
    environment:
      # Жестко прописываем DB_HOST
      DB_HOST: localhost
      # Для остальных переменных оставляем только имена
      - DB_PORT
      - DB_USER
      - DB_PASSWORD
      - DB_NAME
      - TELEGRAM_ERROR_TOKEN
      - TELEGRAM_TOKEN
      - TELEGRAM_USERNAME
      - TELEGRAM_ERROR_USERNAME
      - BINANCE_API_SECRET
      - BINANCE_API_KEY
      - TRADING_BOT_ENABLED

volumes:
  postgres_data: