version: '3.8'

services:
  bot:
    # Указываем Portainer'у, что образ нужно собрать, а не скачивать
    build: .
    # Присваиваем имя собранному образу
    image: binance-bot-all-in-one:latest
    container_name: binance-bot-container
    restart: unless-stopped
    volumes:
      # Очень важно: сохраняем данные PostgreSQL в томе
      - postgres_data:/var/lib/postgresql/14/main
    # Переменные окружения будут добавлены вручную в UI Portainer
    environment:
      DB_HOST: localhost
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      TELEGRAM_ERROR_TOKEN: ${TELEGRAM_ERROR_TOKEN}
      TELEGRAM_TOKEN: ${TELEGRAM_TOKEN}
      TELEGRAM_USERNAME: ${TELEGRAM_USERNAME}
      TELEGRAM_ERROR_USERNAME: ${TELEGRAM_ERROR_USERNAME}
      BINANCE_API_SECRET: ${BINANCE_API_SECRET}
      BINANCE_API_KEY: ${BINANCE_API_KEY}
      TRADING_BOT_ENABLED: ${TRADING_BOT_ENABLED}

volumes:
  postgres_data: